# FOR LOCAL DEVELOPMENT
version: "3"
services:
    joyoabadi:
        restart: always
        build:
            context: .
            dockerfile: deployments/dev.dockerfile
        ports:
            - "8000:8000"
        links:
            - joyoabadidbserver
        volumes:
            # Require parent common package, and dependencies definition is in parent directory.
            # Following volume will simulate local backend repo structure.
            # make sure to run "dep ensure -v" in parent directory (backend).
            - ./:/app
        working_dir: /app
    joyoabadidbmigration:
        restart: on-failure
        image: migrate/migrate
        depends_on:
            - joyoabadidbserver
        links:
            - joyoabadidbserver
        volumes:
            # Require parent common package, and dependencies definition is in parent directory.
            # Following volume will simulate local backend repo structure.
            # make sure to run "dep ensure -v" in parent directory (backend).
            - ./:/go/src/github.com/andre-fajar-n/Joyo-Abadi/backend
        working_dir: /go/src/github.com/andre-fajar-n/Joyo-Abadi/backend
        command: -path=./schema -database postgres://username:password@joyoabadidbserver:5432/joyoabadidb?sslmode=disable up
    joyoabadidbbrowser:
        restart: on-failure
        image: adminer:4-standalone
        ports:
            - "18084:8080"
        depends_on:
            - joyoabadidbserver
        links:
            - joyoabadidbserver
        logging:
            driver: none
        environment:
          - ADMINER_DEFAULT_SERVER=joyoabadidbserver
          - ADMINER_DESIGN=flat
    joyoabadidbserver:
        restart: always
        image: postgres:9.6
        expose:
          - 5432
        logging:
            driver: none
        environment:
          - POSTGRES_DB=joyoabadidb
          - POSTGRES_USER=username
          - POSTGRES_PASSWORD=password
networks:
    default:
        external:
            name: algo-network